[build]
  builder = "nixpacks"
  buildCommand = "cd backend && pip install --upgrade pip && pip install -r requirements.txt"

[start]
  startCommand = "cd backend && gunicorn -w 4 -b 0.0.0.0:$PORT app:app"

[env]
  PORT = "5001"
  DATABASE_URL = "postgresql://postgres:cKlBdWhOQaQcMKJmGWubOnuPAWyAdblr@switchyard.proxy.rlwy.net:54807/railway"
