[build]
  builder = "DOCKERFILE"
  command = "cd backend && pip install -r requirements.txt"

[start]
  command = "bash backend/start.sh"

[env]
  PORT = "5001"
  DATABASE_URL = "postgresql://postgres:cKlBdWhOQaQcMKJmGWubOnuPAWyAdblr@switchyard.proxy.rlwy.net:54807/railway"
