[build]
builder = "Nixpacks"
command = "cd backend && pip install -r requirements.txt"

[start]
command = "cd backend && gunicorn -w 4 -b 0.0.0.0:5000 app:app"

[env]
PORT = "5000"
DATABASE_URL = "postgresql://postgres:cKlBdWhOQaQcMKJmGWubOnuPAWyAdblr@switchyard.proxy.rlwy.net:54807/railway"
JWT_SECRET_KEY = "33be23a8558808478c01430936a9a30b506ee2dd24b66da5c4c60db6f9a133d3"

[service]
name = "mon-portfolio-backend"